### ISSUE TITLE
SystemError:GetRSMaterialNodeMaster() method: bad call flags

### ISSUE THREAD

**Issue by koss998** [gr4ph0s/C4D_RedshiftWrapper_API#5]
Trying my code and your example. Getting:
```
Traceback (most recent call last):
  File "C:\Program Files\Maxon Cinema 4D R23\plugins\Test.pyp", line 614, in Command
self.main()
  File "C:\Program Files\Maxon Cinema 4D R23\plugins\Test.pyp", line 114, in main
rs.SetMat(mat)
  File "C:\Users\tanks\AppData\Roaming\Maxon\Maxon Cinema 4D R23_DBA5903C\python37\libs\RedshiftWrapper\Redshift.py", line 59, in SetMat
self._gvMaster = redshift.GetRSMaterialNodeMaster(mat)
SystemError:GetRSMaterialNodeMaster() method: bad call flags
```

**Comment by gr4ph0s** [comment]
Update redshift, this is a RS bug that should be resolved now :)

**Comment by koss998** [comment]
Thanks! Works like a charm!
